# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		UglyYouth
tagline:	'blog'
description:	'A day is a miniature of eternity'
url:		http://uglyyouth.com
commentsystem:	disqus
disqus:		uglyyouth

author:
  name:		'uglyyouth'
  url:    uglyyouth.com

paginate:	10

# Custom vars
icon:		/assets/images/icon.png
cover:  /assets/images/cover.jpg

social:


  - icon:	github
    url:	https://github.com/uglyyouth
    desc:	Fork me on github

  - icon: feed
    url:  http://uglyyouth/atom.xml
    desc: Subscribe to my feed



menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	uglyyouth
  url:		http://uglyyouth.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
